#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  if [[ "$1" == "gg" ]]; then
    open -a "Google Chrome.app" "about:blank"
  else
    open -a "Google Chrome.app" "$1"
  fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  if [[ "$1" == "gg" ]]; then
    google-chrome about:blank
  else
    google-chrome "$1"
  fi
else
  echo "Unsupported operating system: $OSTYPE"
  exit 1
fi
