#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 PORT_NUMBER"
  exit 1
fi

PORT=$1
PID=$(lsof -t -i:$PORT -sTCP:LISTEN)

if [ -z "$PID" ]; then
  echo "No process found listening on port $PORT"
  exit 1
fi

echo "Killing process $PID listening on port $PORT"
kill -9 $PID

echo "Process killed successfully"
exit 0

