#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 PORT_NUMBER [PORT_NUMBER ...]"
  exit 1
fi

for ARG in "$@"
do
  if [[ "$ARG" =~ - ]]; then
    START_PORT=$(echo "$ARG" | cut -d'-' -f1)
    END_PORT=$(echo "$ARG" | cut -d'-' -f2)

    for ((PORT=START_PORT; PORT<=END_PORT; PORT++)); do
      PID=$(lsof -t -i:$PORT -sTCP:LISTEN)

      if [ -z "$PID" ]; then
        echo "No process found listening on port $PORT"
      else
        echo "Killing process $PID listening on port $PORT"
        kill -9 $PID
      fi
    done
  else
    PORT=$ARG
    PID=$(lsof -t -i:$PORT -sTCP:LISTEN)

    if [ -z "$PID" ]; then
      echo "No process found listening on port $PORT"
    else
      echo "Killing process $PID listening on port $PORT"
      kill -9 $PID
    fi
  fi
done

echo "Processes killed done"
exit 0

